services:
  api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      SPRING_PROFILES_ACTIVE: prod

  web:
    build:
      context: ./frontend-angular
      dockerfile: Dockerfile
    ports:
      - "8100:80"
    depends_on:
      - api
