FROM node:20-alpine AS build
WORKDIR /app

COPY package.json ./
COPY package-lock.json* ./
RUN npm install

COPY . .
RUN npm run build -- --configuration production

FROM nginx:alpine
COPY nginx.conf /etc/nginx/conf.d/default.conf
COPY --from=build /app/dist/frontend-angular-puro/ /usr/share/nginx/html/
EXPOSE 80

